### ISSUE TITLE
getting error of SliderFactory

### ISSUE THREAD

**Issue by nirajketan** [stepzerosolutions/tbslider#4]
getting error of SliderFactory is it something you are working on?

http://prntscr.com/aqzohz

**Comment by nirajketan** [comment]
got the solution

Stepzerosolutions\Tbslider\Setup\UpgradeData

```
public function __construct(
    \Stepzerosolutions\Tbslider\Model\SliderFactory $sliderFactory,
    \Magento\Eav\Model\Config $eavConfig
) {
    $this->sliderFactory = $sliderFactory;
}
```

it just need this update and it works! Thanks

![image](https://cloud.githubusercontent.com/assets/12871321/14436656/5bac9c6a-003b-11e6-8b26-71a51f0e8c94.png)

**Comment by nirajketan** [comment]
Another one

Invalid XML in file C:/wamp/www/app/code/Stepzerosolutions/Tbslider/etc/adminhtml/system.xml:
Element 'field', attribute 'id': [facet 'pattern'] The value 'Extra small device width' is not accepted by the pattern '[a-zA-Z0-9_]{1,}'.

![image](https://cloud.githubusercontent.com/assets/12871321/14436735/ad0745e2-003b-11e6-9950-aaee98580e66.png)

---

Just need field ID as 

<field id="Extra_small_device_width"

**Comment by stepzerosolutions** [comment]
Invalid XML in file C:/wamp/www/app/code/Stepzerosolutions/Tbslider/etc/adminhtml/system.xml:
Element 'field', attribute 'id': [facet 'pattern'] The value 'Extra small device width' is not accepted by the pattern '[a-zA-Z0-9_]{1,}'.

Is a known issue. Will fixed both issues next patch update

**Comment by stepzerosolutions** [comment]
@ngagestudios  Updates are available on Master.
